/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LogRouteImport } from './routes/log'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardBeekeeperRouteImport } from './routes/dashboard/beekeeper'
import { Route as TraceBatchIdRouteImport } from './routes/trace/$batchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBeekeeperRoute = DashboardBeekeeperRouteImport.update({
  id: '/dashboard/beekeeper',
  path: '/dashboard/beekeeper',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceBatchIdRoute = TraceBatchIdRouteImport.update({
  id: '/trace/$batchId',
  path: '/trace/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/log': typeof LogRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/beekeeper': typeof DashboardBeekeeperRoute
  '/trace/$batchId': typeof TraceBatchIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/log': typeof LogRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/beekeeper': typeof DashboardBeekeeperRoute
  '/trace/$batchId': typeof TraceBatchIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/log': typeof LogRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/beekeeper': typeof DashboardBeekeeperRoute
  '/trace/$batchId': typeof TraceBatchIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/log'
    | '/dashboard/admin'
    | '/dashboard/beekeeper'
    | '/trace/$batchId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/log'
    | '/dashboard/admin'
    | '/dashboard/beekeeper'
    | '/trace/$batchId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/log'
    | '/dashboard/admin'
    | '/dashboard/beekeeper'
    | '/trace/$batchId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LogRoute: typeof LogRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardBeekeeperRoute: typeof DashboardBeekeeperRoute
  TraceBatchIdRoute: typeof TraceBatchIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/beekeeper': {
      id: '/dashboard/beekeeper'
      path: '/dashboard/beekeeper'
      fullPath: '/dashboard/beekeeper'
      preLoaderRoute: typeof DashboardBeekeeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace/$batchId': {
      id: '/trace/$batchId'
      path: '/trace/$batchId'
      fullPath: '/trace/$batchId'
      preLoaderRoute: typeof TraceBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LogRoute: LogRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardBeekeeperRoute: DashboardBeekeeperRoute,
  TraceBatchIdRoute: TraceBatchIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
